# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 553a24c32e80834b06ecc758a22d07c66b4ec049372275a2a9577048cfe240bb56433c3848c385183da3b42d74af3fd5b598a5a591c6bd5c794bc90956ba346e

test:
  secret_key_base: f97903a4c1604d98f8fc80b7c0dc55f3e2728846c62a5a146a616c283b1ea034ac0f2b0fdb5fd4572f2e3ed5a350ce2e9bc4d0ed277f118d256ecd345bef45fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
